services:
  # PostgreSQL データベース
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sensechat
      - POSTGRES_USER=sensechat
      - POSTGRES_PASSWORD=sensechat_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sensechat-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sensechat -d sensechat"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (WebSocket Pub/Sub用)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sensechat-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # フロントエンド (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - sensechat-network

  # バックエンド (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://sensechat:sensechat_password@postgres:5432/sensechat
      - USERS_CONFIG=/app/config/users.json
      - LOG_LEVEL=INFO
      - DEBUG=true
      # LLM API設定（.envファイルから読み込み）
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DEFAULT_LLM_PROVIDER=${DEFAULT_LLM_PROVIDER:-openai_gpt4}
    volumes:
      - ./backend:/app
      - ./config:/app/config
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - sensechat-network

  # データベース初期化（初回のみ）
  db-init:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python scripts/init_db.py
    environment:
      - DATABASE_URL=sqlite:///./data/sensechat.db
    volumes:
      - ./backend:/app
      - ./config:/app/config
      - ./data:/app/data
    networks:
      - sensechat-network
    profiles:
      - init

networks:
  sensechat-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  data:
    driver: local
  logs:
    driver: local
